export const environment = {
    articulo_para_baño: import.meta.env.NG_APP_ARTICULO_1,
    articulo_utensillo: import.meta.env.NG_APP_ARTICULO_2,
    articulo_tacho_metal: import.meta.env.NG_APP_ARTICULO_3,
    articulo_cesto_ropa: import.meta.env.NG_APP_ARTICULO_4,
    articulo_organizador_zapatos: import.meta.env.NG_APP_ARTICULO_5,
    articulo_organizador_ropa: import.meta.env.NG_APP_ARTICULO_6,
    articulo_organizador: import.meta.env.NG_APP_ARTICULO_7,
    articulo_balde_mopa: import.meta.env.NG_APP_ARTICULO_8,
    articulo_spray_aceitero: import.meta.env.NG_APP_ARTICULO_9,
    articulo_cesto_basura_chico: import.meta.env.NG_APP_ARTICULO_10,
    articulo_copa_champain: import.meta.env.NG_APP_ARTICULO_11,
    articulo_copa_lineal: import.meta.env.NG_APP_ARTICULO_12,
    articulo_plato_playo: import.meta.env.NG_APP_ARTICULO_13,
    articulo_plato_playo_forjado: import.meta.env.NG_APP_ARTICULO_14,
    articulo_nose: import.meta.env.NG_APP_ARTICULO_15,
    articulo_cesto_nose: import.meta.env.NG_APP_ARTICULO_16,
    articulo_cesto_ratan_contapa: import.meta.env.NG_APP_ARTICULO_18,
};
